about/urls.py
from django.urls import path

from . import views

from django.urls import path

from . import views
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('', views.IndexView.as_view(), name='about'),
    path('resume',views.resume,name='resume'),
    path('projects',views.projects,name='projects')
]

personalWebsite/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('about.urls')),
    path('about/', include('about.urls')),
    path('admin/', admin.site.urls),
]

about/models.py
from django.db import models
from .fields import IntegerRangeField
import datetime
from django.utils import timezone
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator
class Achievement(models.Model):
    date=models.DateField()
    title=models.CharField(max_length=100)
    def __str__(self):
        return self.title
class Project(models.Model):
    date=models.DateField()
    name=models.CharField(max_length=30)
    link=models.URLField()
    imgUrl=models.CharField(max_length=30)
    def __str__(self):
        return self.name


class Skill(models.Model):
    info=models.CharField(max_length=30)

    def __str__(self):
        return self.info

class Interest(models.Model):
    info=models.CharField(max_length=30)

    def __str__(self):
        return self.info

class School(models.Model):
    start_year=models.IntegerField(validators=[MinValueValidator(1998),MaxValueValidator(2100)])
    end_year=models.IntegerField(validators=[MinValueValidator(1998),MaxValueValidator(2100)])
    name=models.CharField(max_length=30)


    def __str__(self):
        return self.name

class Club(models.Model):
    school = models.ForeignKey(School, on_delete=models.CASCADE)
    name=models.CharField(max_length=30)
    def __str__(self):
        return self.name

class Experience(models.Model):
    date=models.DateField()
    info=models.CharField(max_length=100)
    def __str__(self):
        return self.info




# need a certifications model

# also need to look at model relationship thingy by reviewing model documentation in django

about/views.py
import random
from builtins import range

from django.shortcuts import render

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404
from .models import *
from django.template import loader
from django.shortcuts import render
from django.urls import reverse

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
import json
from django.views import generic
class IndexView(generic.ListView):
    template_name = 'index.html'


    #override method
    def get_queryset(self):
        return [i for i in range(10)]

def resume(request):
    template = loader.get_template('resume.html')

    context = {
        'achievements': Achievement.objects.values(),'skills':Skill.objects.values(),
        'clubs':Club.objects.values(),'projects':Project.objects.values(),'schools':School.objects.values(),
        'interests': Interest.objects.values(),'experiences':Experience.objects.values()
    }
    return HttpResponse(template.render(context, request))


def projects(request):
    template=loader.get_template('projects.html')
    context={"projects":Project.objects.values()}

    return HttpResponse(template.render(context, request))

about/templates/index.html
{% load static %}
<head>
    <link rel="stylesheet" type="text/css" href={% static "about/resume-style.css" %} />
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href={% static "about/style.css" %} />
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>About</title>
</head>

<body>
<ul class="nav justify-content-center r">
  <li class="nav-item current">
    <a class="btn btn-light" href={% url 'about:about' %}>Home</a>
  </li>
  <li class="nav-item">
    <a class="btn btn-light" href={% url 'about:resume' %}>Resume</a>
  </li>
  <li class="nav-item">
    <a class="btn btn-light" href={% url 'about:projects' %}>Projects</a>
  </li>
</ul>
<img width="300" id="nithin-pic" src={% static "about/images/nithin_pic.png"%}>
<h1>Nithin Muthukumar</h1>
<div class=description>
    <p id=info>I am a highschool student from Windsor, Canada who is passionate about tech</p>
</div>
<div id="bio">
<a href="https://github.com/nithinmuthukumar"><img width="30" height="30" src={% static "about/images/github_icon.png" %}></a>
<a href="https://www.linkedin.com/in/nithin-muthukumar-681219162/"><img width="30" height="30" src={% static "about/images/linkedin_icon.png" %}></a>
<a href="https://devpost.com/nithinmuthuklumar?ref_content=user-portfolio&ref_feature=portfolio&ref_medium=global-nav"><img width="30" height="30" src={% static "about/images/devpost_icon.png" %}></a>
    <a href="https://nithinmuthukumar.itch.io"><img width="30" height="30" src={% static "about/images/itch_icon.png" %}></a>
</div>



</body>

about/templates/projects.html
{% load static %}
<!--
hidden hides things- pretty cool
also javascript functions are called by events
transitions in css
 -->
<link rel="stylesheet" type="text/css" href={% static "about/resume-style.css" %} />
<script src={% static 'about/Gallery.js' %}> </script>
<head>
    <meta charset="UTF-8">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Projects</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- minimum css file for easy styling-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href={% static "about/project-style.css" %}>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
<body>
<!-- dont have to put text in p tag-->
<ul class="nav justify-content-center r">
  <li class="nav-item">
    <a class="btn btn-light" href={% url 'about:about' %}>Home</a>
  </li>
  <li class="nav-item">
    <a class="btn btn-light" href={% url 'about:resume' %}>Resume</a>
  </li>
  <li class="nav-item current">
    <a class="btn btn-light" href={% url 'about:projects' %}>Projects</a>
  </li>
</ul>
<div class="container">
<div>
    {% for project in projects %}

<div class="card">
  <img src={% static project.imgUrl %} class="card-img-top">
  <div class="card-body">
    <a href="{{ project.link }}" class="btn btn-info">{{ project.name }}</a>
  </div>
</div>
    {% endfor %}
</div>
</div>



</body>

about/templates/resume.html
{% load static %}
<!--
hidden hides things- pretty cool
also javascript functions are called by events
transitions in css
 -->
<link rel="stylesheet" type="text/css" href={% static "about/resume-style.css" %} />
<script src={% static 'about/Gallery.js' %}> </script>
<head>
    <meta charset="UTF-8">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Resume</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- minimum css file for easy styling-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<ul class="nav justify-content-center r">
  <li class="nav-item">
    <a class="btn btn-light" href={% url 'about:about' %}>Home</a>
  </li>
  <li class="nav-item current">
    <a class="btn btn-light" href={% url 'about:resume' %}>Resume</a>
  </li>
  <li class="nav-item">
    <a class="btn btn-light" href={% url 'about:projects' %}>Projects</a>
  </li>
</ul>

<div class="container-fluid">

    <div class="row r">
        <div class="col-md-6">
            <h2>Achievements</h2>
            <ul>
            {% for achievement in achievements%}
                <li>
                <p class="listing"> {{ achievement.title }}</p>
                <p class="date">{{ achievement.date }}</p>
                </li>
            {% endfor %}
            </ul>
        </div>
    <div class="col-md-6">
            <h2>Education</h2>
            {% for school in schools %}
                <h5>{{ school.name }}</h5>
                {% for club in clubs %}
                    <ul>
                    {% ifequal club.school_id school.id %}
                        <li>
                        <p>{{club.name}}</p>
                        </li>
                    {% endifequal %}
                    </ul>
                {% endfor %}
            {% endfor %}

    </div>
    </div>
    <div class="row r">
        <div class="col-md-6">
            <h2>Skills</h2>
            <ul>

                {% for skill in skills %}
                    <li>
                        <p class="listing"> {{ skill.info }}</p>
                     </li>


                {% endfor %}

            </ul>

        </div>
    <div class="col-md-6">
            <h2>Experience</h2>
            <ul>
                {% for experience in experiences %}
                    <li>
                        <p> {{experience.info }}</p>

                     </li>


                {% endfor %}

            </ul>
            <h2>Interests</h2>
            <ul>

                {% for interest in interests %}
                    <li>
                        <p> {{interest.info }}</p>

                     </li>


                {% endfor %}

            </ul>

    </div>
    </div>
</div>

</body>